# Generated by Django 5.0.4 on 2025-02-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WofPuzzle',
            new_name='WosPuzzle',
        ),
    ]
