# Generated by Django 5.0.4 on 2025-03-01 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0002_rename_wofpuzzle_wospuzzle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WosPuzzle',
            new_name='WosPuzz',
        ),
    ]
