# Generated by Django 4.2.23 on 2025-08-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0002_alter_student_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolment',
            unique_together={('school_class', 'student')},
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='seating_position',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='enrolment',
            unique_together={('school_class', 'seating_position'), ('school_class', 'student')},
        ),
    ]
