# Generated by Django 5.0.4 on 2025-03-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0003_rename_wospuzzle_wospuzz'),
    ]

    operations = [
        migrations.AddField(
            model_name='wospuzz',
            name='title',
            field=models.CharField(default='First Puzz', max_length=15),
            preserve_default=False,
        ),
    ]
