# Generated by Django 4.2.23 on 2025-08-09 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0003_alter_enrolment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fortune.schoolclass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='seating_position',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('name', 'seating_position'), ('name', 'number'), ('school_class', 'number')},
        ),
        migrations.DeleteModel(
            name='Enrolment',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
