# Generated by Django 5.0.4 on 2025-03-23 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0004_wospuzz_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='WosPuzz2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('line1', models.CharField(max_length=12)),
                ('line2', models.CharField(max_length=12)),
                ('line3', models.CharField(max_length=12)),
                ('line4', models.CharField(max_length=12)),
                ('hint', models.CharField(blank=True, max_length=25, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
