# Generated by Django 4.2.23 on 2025-09-23 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0004_student_school_class_student_seating_position_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school_class', 'number', 'name')},
        ),
    ]
