# Generated by Django 5.0.4 on 2025-03-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0005_wospuzz2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=12),
        ),
    ]
